-- 코드를 입력하세요
SELECT PRODUCT.PRODUCT_ID, PRODUCT.PRODUCT_NAME, SUM(PRODUCT.PRICE * ORD.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS PRODUCT, FOOD_ORDER AS ORD
WHERE PRODUCT.PRODUCT_ID = ORD.PRODUCT_ID
    AND SUBSTR(ORD.PRODUCE_DATE,1,7) = '2022-05'
GROUP BY PRODUCT.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC